#!/usr/bin/env python3
# https://github.com/VictorGabriel7Dev/cambio-novadax
# https://victorgabriel.dev/projetos/cambio-novadax
# https://victorgabriel.dev.br/projetos/cambio-novadax
# SPDX-License-Identifier: AGPL-3.0-or-later
# Versão: 1.0
#
# Author: Victor Gabriel
# Site: https://victorgabriel.dev
# Site: https://victorgabriel.dev.br
# E-mail: contato@victorgabriel.dev
# GitHub: https://github.com/VictorGabriel7Dev
# LinkedIn: https://linkedin.com/in/victor-gabriel-182a763b9/
# Discord: @VictorGabriel.dev
# Telegram: https://t.me/VictorGabriel_Dev
# Generated by: Claude https://claude.ai

"""
╔══════════════════════════════════════════════════════════════════╗
║              Câmbio NovaDax  ·  Consultor de Cotações            ║
║    Cotação + Taxa de Rede + Custo Total  via API pública         ║
╚══════════════════════════════════════════════════════════════════╝

Uso:
    python Cambio-NovaDax.py 0.012345 DASH
    python Cambio-NovaDax.py 0.012345DASH
    python Cambio-NovaDax.py DASH0.012345

Retorna por cada rede disponível:
  • Cotação em BRL (ou em SOL, quando o par BRL não existe)
  • Mínimo de envio → valor convertido
  • Taxa de rede   → valor convertido
  • Breakdown completo do custo total para pagar + enviar o montante
"""

import re
import sys
import json
import urllib.request
import urllib.error
from typing import Optional

# ─────────────────────────── Definições ────────────────────────────
VIP_LEVEL      = "VIP0"   # nível padrão; ajuste conforme seu cadastro
QUANTIDADE_MEDIA = 15     # quantidade de ofertas a buscar; usa o preço mais alto
USER_AGENT     = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0"

# ─────────────────────────── Constantes ────────────────────────────

COIN_CONF_URL  = "https://www.novadax.com.br/api/config/coinConf"
FEE_CONF_URL   = "https://www.novadax.com.br/api/config/feeConf"
DEPTH_URL = "https://api.novadax.com/v1/market/depth?symbol={symbol}&limit=" + str(QUANTIDADE_MEDIA)

HEADERS_DEPTH = {
    "User-Agent":      USER_AGENT,
    "Accept":          "application/json",
    "Accept-Encoding": "identity",
}

HEADERS_CONF = {
    "User-Agent":       USER_AGENT,
    "Accept":           "application/json",
    "Accept-Language":  "pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3",
    "Accept-Encoding":  "identity",
    "Referer":          "https://www.novadax.com.br/taxas-e-limites",
    "access-token":     "11111111-1111-1111-1111-111111111111",
    "source-mark":      "web",
    "novadax-locale":   "pt-BR",
    "novadax-area":     "BRAZIL",
    "Content-Type":     "application/x-www-form-urlencoded",
    "Cache-Control":    "no-cache",
    "Connection":       "close",
}

# ─────────────────────────── Cores ANSI ────────────────────────────

class C:
    RESET   = "\033[0m"
    BOLD    = "\033[1m"
    CYAN    = "\033[96m"
    YELLOW  = "\033[93m"
    GREEN   = "\033[92m"
    RED     = "\033[91m"
    BLUE    = "\033[94m"
    MAGENTA = "\033[95m"

def title(text: str) -> str:
    return f"{C.BOLD}{C.CYAN}{text}{C.RESET}"

def label(text: str) -> str:
    return text

def value_brl(text: str) -> str:
    return text

def value_coin(text: str) -> str:
    return f"{C.YELLOW}{text}{C.RESET}"

def highlight(text: str) -> str:
    return f"{C.BOLD}{C.GREEN}{text}{C.RESET}"

def section(text: str) -> str:
    return f"{C.BOLD}{C.MAGENTA}{text}{C.RESET}"

def warn(text: str) -> str:
    return f"{C.RED}{text}{C.RESET}"

def dim(text: str) -> str:
    return text

def info(text: str) -> str:
    return f"{C.BLUE}{text}{C.RESET}"

# ─────────────────────────── Utilitários ───────────────────────────

def oito_digitos(value: float) -> float:
    """Arredonda para 8 casas decimais."""
    return round(value, 8)


def parse_args(raw: str) -> tuple[str, float]:
    """
    Aceita qualquer combinação de número+moeda ou moeda+número:
        0.012345DASH  /  DASH0.012345  /  0.012345 DASH
    Retorna (MOEDA, quantidade).
    """
    raw = raw.replace(",", ".").strip()
    m = re.match(r'^(\d+(?:\.\d+)?)\s*([A-Za-z]+)$', raw)
    if m:
        return m.group(2).upper(), float(m.group(1))
    m = re.match(r'^([A-Za-z]+)\s*(\d+(?:\.\d+)?)$', raw)
    if m:
        return m.group(1).upper(), float(m.group(2))
    raise ValueError(f"Formato inválido: '{raw}'. Use ex: 0.012345DASH")


def fetch_json(url: str, headers: Optional[dict] = None) -> dict:
    req = urllib.request.Request(url, headers=headers or {})
    # Solicita conteúdo sem compressão para evitar erros de decodificação gzip
    if "Accept-Encoding" not in req.headers:
        req.add_header("Accept-Encoding", "identity")
    with urllib.request.urlopen(req, timeout=15) as resp:
        raw = resp.read()
        # Descomprime gzip caso o servidor ignore o Accept-Encoding
        if resp.info().get("Content-Encoding") == "gzip":
            import gzip
            raw = gzip.decompress(raw)
        return json.loads(raw.decode("utf-8"))


def fetch_depth(symbol: str) -> Optional[dict]:
    """Busca o livro de ordens. Retorna None se o par não existir."""
    try:
        data = fetch_json(DEPTH_URL.format(symbol=symbol), HEADERS_DEPTH)
        if data.get("message", "").lower().find("not exist") != -1:
            return None
        if data.get("code") != "A10000":
            return None
        return data
    except Exception:
        return None


def best_ask(depth_data: dict) -> Optional[float]:
    """Retorna o maior preço entre os asks."""
    asks = depth_data.get("data", {}).get("asks", [])
    if not asks:
        return None
    return max(float(a[0]) for a in asks if a[0])


def separator(char: str = "─", width: int = 62) -> str:
    return dim(char * width)


# ─────────────────────────── Saída formatada ───────────────────────

W  = 66   # largura dos separadores
LW = 38   # largura da coluna de label nas tabelas
RW = 20   # largura da coluna de valor nas tabelas

def sep(char: str = "─") -> str:
    return dim(char * W)

def blank() -> None:
    print()

def ssep(title_str: str) -> None:
    """Separador de seção com título embutido."""
    print(f"  {dim('── ')}{dim(title_str)}")

def trow(lbl: str, val: str, color_fn=None) -> None:
    """
    Linha de tabela com colunas fixas.
    O padding é aplicado ao texto puro ANTES de colorir,
    evitando desalinhamento por escapes ANSI.
    """
    color_fn = color_fn or value_brl
    print(f"  {label(lbl.ljust(LW))}{color_fn(val.rjust(RW))}")

def tdiv(char: str = "·") -> None:
    print(f"  {dim((char * (LW + RW + 2)))}")

def ttotal(lbl: str, val: str) -> None:
    print(f"  {highlight(lbl.ljust(LW))}{highlight(val.rjust(RW))}")


def print_header(moeda: str, quantidade: float) -> None:
    qtd_str = f"{quantidade:.8f}".rstrip("0").rstrip(".")
    blank()
    print(sep("═"))
    print(f"  {title('NovaDax')}  {dim('·')}  {dim('Câmbio Cripto')}")
    print(f"  {dim('Consultando')}  {value_coin(qtd_str + ' ' + moeda)}")
    print(sep("═"))
    blank()


def print_network_header(currency: str, chain: str, idx: int, total: int) -> None:
    counter = dim(f"  [{idx}/{total}]") if total > 1 else ""
    print(f"  {section('▶  ' + currency)}  {dim('·')}  {info(chain)}{counter}")
    print(sep())


def print_market_info(currency: str, cotacao: float, minimo: float,
                      taxa_rede: float, fee_type: str, is_sol: bool) -> None:
    """
    Bloco 1 — Cotação atual + limites e taxa de saque da rede.
    Redes com feeType 'dynamic' não têm taxa conhecida antecipadamente.
    """
    sym = "SOL" if is_sol else "BRL"

    if is_sol:
        cot_r    = oito_digitos(1 / cotacao)
        min_r    = oito_digitos(minimo    * cot_r)
        tax_r    = oito_digitos(taxa_rede * cot_r)
        cot_str  = f"{cot_r:.8f} {sym}"
        min_str  = f"{min_r:.8f} {sym}"
        tax_str  = f"{tax_r:.8f} {sym}"
    else:
        cot_str  = f"R$ {cotacao:,.2f}"
        min_str  = f"R$ {minimo    * cotacao:,.2f}"
        tax_str  = f"R$ {taxa_rede * cotacao:,.2f}"

    ssep("Mercado")
    blank()
    trow("  Cotação atual (1 " + currency + ")", cot_str, value_brl)
    blank()
    ssep("Limites e taxas de rede")
    blank()
    trow("  Mínimo de depósito",
         f"{minimo:.8f} {currency}", dim)
    print(f"  {dim(' ' * LW)}{'→  ' + min_str}")
    blank()
    if fee_type == "dynamic":
        print(f"  {warn('  Taxa de saque (dynamic): valor definido no momento do saque.')}")
        print(f"  {warn('  Não é possível calcular o custo total com antecedência.')}")
    else:
        trow("  Taxa de saque da rede",
             f"{taxa_rede:.8f} {currency}",
             value_coin if taxa_rede > 0 else dim)
        print(f"  {dim(' ' * LW)}{'→  ' + tax_str}")
    blank()


def print_breakdown(moeda: str, quantidade: float, cotacao: float,
                    taxa_rede: float, is_sol: bool,
                    taker_fee: float, taker_div: float) -> float:
    """
    Bloco 2 — Quanto precisa ser comprado e enviado.

    Conceitos:
      • "Precisa COMPRAR"  = quantidade + taxa_rede + taxa_de_compra
           → o que você paga na exchange para que, após a taxa de compra
             e a taxa de saque, chegue exatamente `quantidade` ao destino.
      • "Precisa ENVIAR"   = quantidade + taxa_rede
           → o que sai da sua carteira; a rede desconta `taxa_rede`
             e entrega `quantidade` no destino.

    Fórmula BRL:
      val_brl    = quantidade × cotacao
      taxa_e_brl = taxa_rede  × cotacao
      subtotal   = val_brl + taxa_e_brl
      total_brl  = subtotal / taker_div        (≡ subtotal + taxa_compra)

    Fórmula moeda:
      a_enviar   = quantidade + taxa_rede
      a_comprar  = a_enviar   / taker_div
    """
    val_brl    = quantidade * cotacao
    taxa_e_brl = taxa_rede  * cotacao
    subtotal   = val_brl + taxa_e_brl
    tcompra    = subtotal * taker_fee
    total_brl  = subtotal / taker_div

    a_enviar   = quantidade + taxa_rede
    tcompra_c  = oito_digitos(a_enviar * taker_fee)
    a_comprar  = oito_digitos(a_enviar / taker_div)

    pct = taker_fee * 100

    ssep("Custo para comprar e enviar")
    blank()
    print(f"  {dim('  Destino receberá exatamente :  ')}"
          f"{value_coin(f'{quantidade:.8f} {moeda}')}")
    print(f"  {dim('  Taxa de compra (taker)       :  ')}"
          f"{dim(f'{pct:.2f}%  ({VIP_LEVEL})')}")
    blank()

    if not is_sol:
        ssep("Em reais (BRL)")
        blank()
        trow(f"  Valor da moeda  "
             f"({quantidade:.4f} × R${cotacao:,.2f})",
             f"R$ {val_brl:,.2f}", value_brl)
        trow(f"  Taxa de saque   "
             f"({taxa_rede:.4f} × R${cotacao:,.2f})",
             f"R$ {taxa_e_brl:,.2f}",
             value_coin if taxa_rede > 0 else dim)
        tdiv("·")
        trow("  Subtotal", f"R$ {subtotal:,.2f}", value_brl)
        trow(f"  Taxa de compra  ({pct:.2f}% s/ subtotal)",
             f"R$ {tcompra:,.2f}", value_coin)
        tdiv("─")
        ttotal("  TOTAL A PAGAR (BRL)", f"R$ {total_brl:,.2f}")
        blank()

    ssep(f"Em {moeda}")
    blank()
    trow("  Quantidade que chegará ao destino",
         f"{quantidade:.8f} {moeda}", dim)
    trow("  Taxa descontada pela rede no envio",
         f"{taxa_rede:.8f} {moeda}",
         value_coin if taxa_rede > 0 else dim)
    tdiv("·")
    trow("  Precisa ENVIAR  (sai da sua carteira)",
         f"{a_enviar:.8f} {moeda}", value_brl)
    trow(f"  Taxa de compra  ({pct:.2f}%)",
         f"{tcompra_c:.8f} {moeda}", value_coin)
    tdiv("─")
    ttotal(f"  Precisa COMPRAR na exchange",
           f"{a_comprar:.8f} {moeda}")
    blank()

    return a_comprar


def print_sol_conversion(currency: str, cotacao_ask: float,
                         a_comprar_moeda: float, sol_chain_data: dict,
                         taker_fee: float, taker_div: float) -> None:
    """
    Bloco 3 — Conversão quando o par não existe em BRL (usa SOL_MOEDA).
    Calcula quanto SOL comprar para obter a_comprar_moeda unidades de MOEDA.
    """
    sol_necessario = a_comprar_moeda / cotacao_ask
    sol_tcompra    = sol_necessario * taker_fee
    sol_a_comprar  = sol_necessario / taker_div

    tcompra_c  = oito_digitos(a_comprar_moeda * taker_fee)
    total_c    = oito_digitos(a_comprar_moeda / taker_div)

    chain = sol_chain_data.get("chain", "Solana (SOL)")
    pct   = taker_fee * 100

    print(sep())
    print(f"  {section('↔  Conversão via SOL')}  {dim('·')}  {info(chain)}")
    print(sep())
    blank()

    ssep(f"Em {currency}")
    blank()
    trow(f"  Necessário ({currency})",
         f"{a_comprar_moeda:.8f} {currency}", value_coin)
    trow(f"  Taxa de compra  ({pct:.2f}%)",
         f"{tcompra_c:.8f} {currency}", value_coin)
    tdiv("─")
    ttotal(f"  Precisa COMPRAR ({currency})",
           f"{total_c:.8f} {currency}")
    blank()

    ssep("Em SOL")
    blank()
    trow("  SOL necessário para a troca",
         f"{sol_necessario:.4f} SOL", value_brl)
    trow(f"  Taxa de compra  ({pct:.2f}%)",
         f"{sol_tcompra:.4f} SOL", value_coin)
    tdiv("─")
    ttotal("  Precisa COMPRAR (SOL)",
           f"{sol_a_comprar:.4f} SOL")
    blank()




# ──────────────────────────── Main ─────────────────────────────────

def main() -> None:
    # ── parse de argumentos ──────────────────────────────────────────
    raw = " ".join(sys.argv[1:]).strip()
    if not raw:
        print(f"\n  {warn('Uso:')}  python Cambio-NovaDax.py 0.012345DASH\n")
        sys.exit(1)

    try:
        moeda, quantidade = parse_args(raw)
    except ValueError as e:
        print(f"\n  {warn(str(e))}\n")
        sys.exit(1)

    print_header(moeda, quantidade)

    # ── busca feeConf (taxas de negociação) ──────────────────────────
    try:
        fee_conf = fetch_json(FEE_CONF_URL)
        fees_list = fee_conf.get("data", {}).get("fees", [])
        taker_entry = next((f for f in fees_list if f.get("type") == "taker"), {})
        taker_fee = float(taker_entry.get(VIP_LEVEL, {}).get("commissionFee", 0.006))
    except Exception:
        taker_fee = 0.006
    taker_div = 1.0 - taker_fee

    # ── busca coinConf ───────────────────────────────────────────────
    try:
        conf = fetch_json(COIN_CONF_URL, HEADERS_CONF)
    except Exception as e:
        print(f"\n  {warn(f'Erro ao buscar coinConf: {e}')}\n")
        sys.exit(1)

    # ── cache de profundidade ────────────────────────────────────────
    depth_cache: dict[str, Optional[dict]] = {}

    def get_depth(symbol: str) -> Optional[dict]:
        if symbol not in depth_cache:
            depth_cache[symbol] = fetch_depth(symbol)
        return depth_cache[symbol]

    # ── normaliza send → lista de chain_entries ──────────────────────
    # Estrutura atual: data.send = {
    #   "individual": [{"cryptoChains": [...], "currency": ..., ...}],
    #   "institution": [...]
    # }
    # Cada cryptoChain tem: currency, chain, minimum, commissionBasicAmount,
    #                       feeType, burnRate
    def extract_chains(conf_data: dict) -> list[dict]:
        send = conf_data.get("data", {}).get("send", {})

        # ── Formato atual: dict com "individual" contendo cryptoChains ──
        if isinstance(send, dict) and "individual" in send:
            entries = []
            for individual in send["individual"]:
                for ce in individual.get("cryptoChains", []):
                    entries.append(ce)
            return entries

        # ── Formato alternativo: send é lista plana ──────────────────
        if isinstance(send, list):
            return [
                {
                    "currency":              item.get("currency", ""),
                    "chain":                 item.get("chain") or item.get("currency", ""),
                    "minimum":               item.get("minimum", 0),
                    "commissionBasicAmount": item.get("fee",
                                            item.get("commissionBasicAmount", 0)),
                }
                for item in send
            ]

        return []

    chain_entries = extract_chains(conf)
    encontrou = False

    # índice rápido das redes SOL para conversão final
    sol_chains = [ce for ce in chain_entries if ce.get("currency") == "SOL"]

    # filtra só as entradas da moeda pedida para saber o total (para counter)
    moeda_entries = [ce for ce in chain_entries if ce.get("currency") == moeda]
    total_redes   = len(moeda_entries)
    idx_rede      = 0

    for chain_entry in chain_entries:
        currency = chain_entry.get("currency", "")

        if moeda and currency != moeda:
            continue

        idx_rede += 1
        chain     = chain_entry.get("chain", currency)
        minimum   = float(chain_entry.get("minimum", 0))
        taxa_rede = float(chain_entry.get("commissionBasicAmount", 0))
        fee_type  = chain_entry.get("feeType", "")

        # ── cotação BRL ──────────────────────────────────────────────
        is_sol    = False
        depth_brl = get_depth(f"{currency}_BRL")

        if depth_brl is None:
            depth_sol = get_depth(f"SOL_{currency}")
            if depth_sol is None:
                print(f"  {warn(f'Par inexistente: {currency}_BRL e SOL_{currency}.')}")
                print(sep())
                blank()
                continue
            is_sol = True
            depth  = depth_sol
        else:
            depth  = depth_brl

        cotacao = best_ask(depth)
        if cotacao is None:
            print(f"  {warn(f'Sem dados de cotação para {currency}.')}")
            print(sep())
            blank()
            continue

        encontrou = True
        print_network_header(currency, chain, idx_rede, total_redes)
        print_market_info(currency, cotacao, minimum, taxa_rede, fee_type, is_sol)

        if fee_type == "dynamic":
            print(sep("─"))
            blank()
            continue

        total_coin = print_breakdown(moeda, quantidade, cotacao,
                                     taxa_rede, is_sol,
                                     taker_fee, taker_div)

        if is_sol:
            sol_chain = next(
                (s for s in sol_chains if s.get("chain", "") == "Solana (SOL)"),
                sol_chains[0] if sol_chains else {}
            )
            print_sol_conversion(currency, cotacao, total_coin, sol_chain,
                                 taker_fee, taker_div)

        print(sep("─"))
        blank()

    if not encontrou:
        print(f"  {warn(f'Moeda não encontrada: {moeda}')}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
